name: Build and Deploy to Docker Hub and Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Make Maven Wrapper executable
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests


    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Build Docker image
    #   run: docker build -t ${{ secrets.DOCKER_REPO }} .

    # - name: Push Docker image
    #   run: docker push ${{ secrets.DOCKER_REPO }}


    - name: Set Docker Tag
      id: vars
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "tag=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
        else
          echo "tag=build-${{ github.run_number }}" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_REPO }}:${{ steps.vars.outputs.tag }} .

    - name: Push Docker image with version tag
      run: docker push ${{ secrets.DOCKER_REPO }}:${{ steps.vars.outputs.tag }}

    - name: Tag and push latest (only on push to main)
      if: github.event_name == 'push'
      run: |
        docker tag ${{ secrets.DOCKER_REPO }}:${{ steps.vars.outputs.tag }} ${{ secrets.DOCKER_REPO }}:latest
        docker push ${{ secrets.DOCKER_REPO }}:latest

